from typing_extensions import Annotated
from pydantic import AfterValidator
from azure_connectors.validation.validators import validate_storage_account_name, validate_azure_sql_server_address

StorageAccountName = Annotated[str, AfterValidator(validate_storage_account_name)]
AzureSqlServerDomainName = Annotated[str, AfterValidator(validate_azure_sql_server_address)]
